### ISSUE TITLE
the Zotero plugin is not preinstalled in ONLYOFFICE  5.6.4 (MacOsX)

### ISSUE THREAD

**Issue by max-talanov** [ONLYOFFICE/plugin-zotero#20]
Dear all.
Could you please help me?
I have failed to find the Zotero plugin in the latest ONLYOFFICE  5.6.4 (MacOsX).
Please see screenshot below:
![Screen Shot 2020-09-26 at 07 30 37](https://user-images.githubusercontent.com/548287/94330157-64552600-ffca-11ea-8e5e-e3e02901712d.png)

Could you please help me with the issue to install the Zotero plugin for ONLYOFFICE  5.6.4 (MacOsX)?
Thank you so much in advance.

**Comment by m4chi** [comment]
I have the same problem with the Linux ONLYOFFICE Desktop Editors version 5.6.4.20.

**Comment by guikool** [comment]
I've observed same issue for Windows ONLYOFFICE Desktop Editors version 6.0.2.10
I try to manually intall it without success. Is it planed to push Zotero on this version. This is one of the main caveats for a full migration to this beautifull suite.

**Comment by DenisDeeSign** [comment]
Hello,
Zotero plugin is not included in Desktop Editors so far because of some issues. We will discuss including of it in next major version with our dev team.
@guikool, how did you install the plugin? Please learn more [there](https://api.onlyoffice.com/plugin/installation).

**Comment by chrono35** [comment]
Hi,
I observe the same problem on macOS Big Sur for ONLYOFFICE Desktop Editors version 6.1
I also tried to install it manually without success. 
I couldn't find what kind of archive is expected (zip, rar, tar ...)
Many of us are waiting for this integration.

**Comment by DenisDeeSign** [comment]
Hello @chrono35,
you should change extension of .zip archive with plugin source code to .plugin. You can find detailed instruction [here](https://api.onlyoffice.com/plugin/installation).

**Comment by nkandrian** [comment]
> Hello @chrono35,
> you should change extension of .zip archive with plugin source code to .plugin. You can find detailed instruction [here](https://api.onlyoffice.com/plugin/installation).

Thanks! The instructions linked worked for me (OS Big Sur 11.2) after unzipping and re-zipping _only_ the files in the "src" subfolder.

**Comment by ShockwaveNN** [comment]
Right now README file contains all installation instructions and details about where plugin installed by default so I'm closing this
