### ISSUE TITLE
/var/www/onlyoffice does not exist!

### ISSUE THREAD

**Issue by faloude** [ONLYOFFICE/plugin-zotero#25]
Under Linux Mint 20 with OnlyOffice DesktopEditors installed the folder **/var/www/onlyoffice** that you mention in the readme does not exist. I found it under: **/home/user/.var/app/org.onlyoffice.desktopeditors/data/onlyoffice/desktopeditors/sdjk-plugins/src**.

Is this worth editing in the readme of this plugin?

**Comment by ShockwaveNN** [comment]
This is instruction for instaling Zotero plugin in DocumentServer, not DesktopEditors

To install it to DesktopEditors your should use this [method](https://api.onlyoffice.com/plugin/installation)

**Comment by faloude** [comment]
Thanks so much man. I'll close this embarassing ticket.
