### ISSUE TITLE
What is "Document Server config"?

### ISSUE THREAD

**Issue by faloude** [ONLYOFFICE/plugin-zotero#26]
As the readme mentions I can (ab)use the issues tab for help requests, I gladly take the offer!

The readme instructs to edit the **Document Server config**. What in god's name is the file you're speaking about? I've been pulling my hair out :(

**Comment by ShockwaveNN** [comment]
> The readme instructs to edit the Document Server config.

This depends of which connector are you using.
And just to be clear - please note version of DocumentServer and host os for DocumentServer you're using

**Comment by ShockwaveNN** [comment]
This issue was closed due to no response.
