### ISSUE TITLE
Paper in a group are not found

### ISSUE THREAD

**Issue by thorstenwagner** [ONLYOFFICE/plugin-zotero#47]
If a paper is only in a group library, it is not found by this plugin. I'm using onlyoffice through the web interface in owncloud. 
Would be great to see that fixed.

**Comment by VladimirProkofiev52** [comment]
Hello.
@thorstenwagner, I can confirm - this is bug, issue 56359 in our private issue tracker.
Thank you for report.

**Comment by nolden** [comment]
@ShockwaveNN I saw there was a fix already: https://github.com/ONLYOFFICE/plugin-zotero/commit/8878c2eeb761737a22e2ef95ac2c180159e45b23 Which version of OnlyOffice iwill this be integrated, or is it already?

**Comment by ShockwaveNN** [comment]
@nolden Oh, thanks, this issue should be resolved, seems we forgot to close this

You should install plugin from master
