### ISSUE TITLE
How do i install this in documentserver-de?

### ISSUE THREAD

**Issue by madsi1m** [ONLYOFFICE/plugin-zotero#5]
Hi we are running https://hub.docker.com/r/onlyoffice/documentserver-de and can not install zotero plugin.

I have put the contents of src in /var/www/onlyoffice/documentserver/sdkjs-plugins/zotero and zotero does not show up in the plugins tab.

Am i missing a step?

Cheers

**Comment by Eloncase** [comment]
Hi, first of all plugin is not released yet so it may not work properly.

Despite that I'm not sure what your problem is. Your steps do seem to be correct.
I'm running it like that, which in fact does the same thing.
```
docker run -i -t -d -p 9090:80 -v /path/to/repository/plugin-zotero/src/:/var/www/onlyoffice/documentserver/sdkjs-plugins/zotero onlyoffice/documentserver
```
And don't forget to switch repository to `develop` branch.

**Comment by madsi1m** [comment]
Wonder what the difference between onlyoffice/documentserver and onlyoffice/documentserver-de are

**Comment by Eloncase** [comment]
Just did the same with DE version, worked fine.
```
docker run -i -t -d -p 9090:80 -v /root/plugin-zotero/src/:/var/www/onlyoffice/documentserver/sdkjs-plugins/zotero onlyoffice/documentserver-de
```

**Comment by madsi1m** [comment]
Interesting, I was starting the container and copying the files in once it was up. Having them there before or at time of creation seems to do the trick.
