### ISSUE TITLE
I do not understan instructions to install Zotero plugin into desktop (Linux Debian)

### ISSUE THREAD

**Issue by tvrbanec** [ONLYOFFICE/plugin-zotero#50]
Can you just give zotero.plugin which just works? Whatever I do, it failed to install.
Thank you.

**Comment by ShockwaveNN** [comment]
Hi, use this
[plugin-zotero-master.zip](https://github.com/ONLYOFFICE/plugin-zotero/files/8725836/plugin-zotero-master.zip)
(rename it from  `plugin-zotero-master.zip` to `plugin-zotero-master.plugin` after download

**Comment by tvrbanec** [comment]
Thank you!

**Comment by tvrbanec** [comment]
Zotero plugin is not working with full features, only with insert Bibliography. One cannot insert references in the text.

**Comment by ShockwaveNN** [comment]
@tvrbanec Yes, you're right

We got issue about that
https://github.com/ONLYOFFICE/plugin-zotero/issues/19
