### ISSUE TITLE
confused about installation

### ISSUE THREAD

**Issue by asheetal** [ONLYOFFICE/plugin-zotero#55]
The desktop version says 
```
Archive the plugin files (the archive must contain config.json, index.html, and pluginCode.js).
```
Where are these files?

**Comment by ShockwaveNN** [comment]
They are literally here in this repo (first two and pluginCode.js is generic name for [those files ](https://github.com/ONLYOFFICE/plugin-zotero/tree/master/scripts):

![image](https://user-images.githubusercontent.com/668524/181970714-e3696fb2-07eb-4481-9328-2440af7f17d6.png)

Or you can simply use release version of plugin https://github.com/ONLYOFFICE/plugin-zotero/releases

**Comment by asheetal** [comment]
Thanks....the released plugin worked.
